web:
  build: .
  dockerfile: .dockerfile
  command: python manage.py runserver 0.0.0.0:5000
  volumes:
    - ./:/usr/src/app
  links:
   - postgres
   - elasticsearch
  ports:
   - "5000:5000"
  environment:
    - DEBUG=True
    - DEV=True
    - DATABASE_URL=postgres://postgres:@postgres:5432/postgres
    - ELASTICSEARCH_URL=http://elasticsearch:9200
    - SECRET_KEY=notasecretreplaceme
postgres:
  image: postgres
  ports:
   - "5432:5432"
elasticsearch:
  image: orchardup/elasticsearch
  ports:
    - "9200:9200"
