---
# tasks file for docker-compose
- name: Install docker-compose
  get_url:
    url: https://github.com/docker/compose/releases/download/{{docker_compose_version}}/docker-compose-{{ansible_system}}-{{ansible_architecture}}
    dest: "{{'{}/docker-compose'.format(docker_compose_path)}}"
    mode: "{{docker_compose_mode}}"
