---

- name: Create release directory
  file: path={{ release_dir }} state=directory

- name: Checkout code branch from git
  git:
    repo: 'https://github.com/datalets/public-health-ch'
    dest: "{{ release_dir }}"

- name: Copy Docker site configuration
  template:
    src: docker-compose.j2
    dest: "{{ release_dir }}/docker-compose.yml"

- name: Deploy Docker site
  shell: docker-compose build
